services:
  - type: web
    name: Orphee_portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application
    # Ce champ exécute les migrations et les statiques avant le démarrage
    preDeployCommand: python manage.py collectstatic --no-input; python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9